---
- name: 2.8 Enable user namespace support (Scored)
  debug: msg="*** not covered by this playbook"
  tags:
   - scored
   - section2.8

- name: 2.9 Confirm default cgroup usage (Scored)
  shell: ps -ef | grep docker | grep [c]group-parent
  register: res
  failed_when: res.rc == 0
  changed_when: res.rc == 0
  tags:
   - scored
   - section2.9

- name: 2.10 Do not change base device size until needed (Scored)
  shell: ps -ef | grep docker | grep [d]m.basesize
  register: res
  failed_when: res.rc == 0
  changed_when: res.rc == 0
  always_run: yes
  tags:
   - scored
   - section2.10

- name: 2.11 Use authorization plugin (Scored)
  debug: msg="*** not covered by this playbook"
  tags:
   - scored
   - section2.11

- name: 2.12 Configure centralized and remote logging (Scored)
  shell: "ps -ef | grep docker | grep [l]og-driver"
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.12

- name: 2.13 Disable operations on legacy registry (v1) (Scored)
  shell: ps -ef | grep docker | grep [d]isable-legacy-registry
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.13

